openapi: 3.0.0
info:
  title: Team Harpoon
  version: 1.0.0
servers:
  - url: http://web-01.okoth.tech/api/v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Auth
  - name: User
  - name: Event
paths:
  /users/signup:
    post:
      tags:
        - Auth
      summary: Sign Up
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Savadoww
                email: savadow@example.com
                password: secret
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/google:
    post:
      tags:
        - Auth
      summary: Google
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Savadow
                email: savadow@example.com
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/twitter:
    post:
      tags:
        - Auth
      summary: Twitter
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Savadow
                email: savadow@example.com
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/{id}:
    get:
      tags:
        - User
      summary: Get User
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - User
      summary: Update User
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Nedum
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /events:
    get:
      tags:
        - Event
      summary: Get All Events
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Event
      summary: Create Event
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Savadow's Event
                description: Come chill with me
                location: PH
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
